### ISSUE TITLE
Not working when using Turborepo and Next.js

### ISSUE THREAD

**Issue by pixeleate** [FirebaseExtended/firebase-framework-tools#37]
First of all, should this work with `Turborepo`? If not, that's okay, I don't want to be frustrated with this if not working with Turborepo is a known issue.

But if it should work, I don't know what I'm doing wrong, I have a very basic setup, it's the basic `Turborepo` template, what you get by running `npx create-turbo@latest` + my Firebase config files in this folder `apps/web`.

Doesn't matter if I put the files in a different place, the result is the same.

![Screen Shot 2022-09-22 at 5 09 07 PM](https://user-images.githubusercontent.com/1545853/191860387-99896db0-bb1d-4a19-b776-17b102bf487c.png)

Exactly the same config, in a project without `Turborepo` works like a charm

**Comment by atanaskanchev** [comment]
I have the same issue, but with NX. I've tried initialising hosting in the root of the repo and inside the app folder, 
however, `firebase serve` fails with `Error: Epic fail.
    at prepareFrameworks (/opt/homebrew/Cellar/firebase-cli/11.16.1/libexec/lib/node_modules/firebase-tools/lib/frameworks/index.js:228:19)
    at async serve (/opt/homebrew/Cellar/firebase-cli/11.16.1/libexec/lib/node_modules/firebase-tools/lib/serve/index.js:21:9)`
