### ISSUE TITLE
Error: > Couldn't find a `pages` directory.

### ISSUE THREAD

**Issue by innellea** [FirebaseExtended/firebase-framework-tools#68]
I tried several ways to deploy a Nextjs app using the experimental web frameworks.

I moved pages in and out of the src folder without any luck. Interestingly, it works with ```firebase serve```.

```
> Build error occurred
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/workspace/node_modules/next/dist/lib/find-pages-dir.js:86:19)
    at /workspace/node_modules/next/dist/build/index.js:114:63
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/workspace/node_modules/next/dist/build/index.js:72:29). For more details see the logs at https://console.cloud.google.com/cloud-build/builds;region=us-central1/3e07950f-6c05-445e-babf-c11ca93717b1?project=837516068454.
```

**Comment by innellea** [comment]
Just a quick update, I had this in my package.json:
```
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    **"gcp-build": "next build",**
  },

I believe gcp-build is a leftover, which is needed for App Engine in the past.
```
