### ISSUE TITLE
[NextJS] - Failed to deploy API Routes with App Folder

### ISSUE THREAD

**Issue by AlexBrasileiro** [FirebaseExtended/firebase-framework-tools#79]
**Settings:**

Operating System: Mac
Node Version: v16.16.0
Firebase CLI: v12.0.0
Next: v13.4.2

----

**Error Description:**

When trying to deploy (passing the ```firebase deploy``` command), when adding the **Api directory with Routes** (as shown in the image in the attachment), for example to use backend functions executed only by the Node server side (such as an API to fetch data in the database), the deploy attempt fails 😢

Without the api folder inside the app folder, deploy proceeds normally 🤗

----

What is the correct approach to fix this (use Node/Backend functions on the project)? 

- Use Firebase Cloud Functions (Callable Functions) in these cases? 
- Use the previous version of Next (pages and api folder inside of the root folder of the project)?
- Use only react/next server-components and don't use the Route Handlers? 

Below is the firebase-debug.log file generated in the attempt to deploy described above.

```log
[debug] [2023-05-14T19:46:48.709Z] ----------------------------------------------------------------------
[debug] [2023-05-14T19:46:48.710Z] Command:       /Users/user/.nvm/versions/node/v16.16.0/bin/node /Users/user/.nvm/versions/node/v16.16.0/bin/firebase deploy
[debug] [2023-05-14T19:46:48.711Z] CLI Version:   11.29.1
[debug] [2023-05-14T19:46:48.711Z] Platform:      darwin
[debug] [2023-05-14T19:46:48.711Z] Node Version:  v16.16.0
[debug] [2023-05-14T19:46:48.712Z] Time:          Sun May 14 2023 16:46:48 GMT-0300 (Brasilia Standard Time)
[debug] [2023-05-14T19:46:48.712Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-05-14T19:46:48.773Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-05-14T19:46:48.774Z] > authorizing via signed-in user (user@gmail.com)
[debug] [2023-05-14T19:46:48.774Z] [iam] checking project nextjs-firebase-test for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-05-14T19:46:48.776Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions [none]
[debug] [2023-05-14T19:46:48.776Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions x-goog-quota-user=projects/nextjs-firebase-test
[debug] [2023-05-14T19:46:48.776Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-05-14T19:46:49.739Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions 200
[debug] [2023-05-14T19:46:49.739Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/nextjs-firebase-test:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-05-14T19:46:49.740Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions [none]
[debug] [2023-05-14T19:46:49.741Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2023-05-14T19:46:50.736Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions 200
[debug] [2023-05-14T19:46:50.736Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/nextjs-firebase-test/serviceAccounts/nextjs-firebase-test@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2023-05-14T19:46:50.738Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/nextjs-firebase-test [none]
[debug] [2023-05-14T19:46:51.137Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/nextjs-firebase-test 200
[debug] [2023-05-14T19:46:51.137Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/nextjs-firebase-test {"projectId":"nextjs-firebase-test","projectNumber":"863676582419","displayName":"NextJS Firebase Test ","name":"projects/nextjs-firebase-test","resources":{"hostingSite":"nextjs-firebase-test"},"state":"ACTIVE","etag":"1_b68ede31-c607-42c6-8f32-3e57e9bdc093"}
[debug] [2023-05-14T19:47:05.405Z] TypeError: Cannot read properties of null (reading 'endsWith')
    at ɵcodegenPublicDirectory (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:206:56)
    at async prepareFrameworks (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/frameworks/index.js:294:13)
    at async deploy (/Users/user/.nvm/versions/node/v16.16.0/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.

```

![Screenshot 2023-05-14 at 16 56 41](https://github.com/FirebaseExtended/firebase-framework-tools/assets/15070031/8ab070b7-4b0c-488e-bb68-bf39c58c4d04)

**Comment by AlexBrasileiro** [comment]
Closing this issue, as @jamesdaniels [commented on this](https://github.com/firebase/firebase-tools/issues/5836#issuecomment-1548543866), to work correctly it is necessary to update the Firebase CLI
